---USER DETAILS TABLE---
create table user_details( user_id int generated by default as identity (start with 100 increment by 1) primary key,
                           user_name varchar2(20) not null
                          ,email_id varchar2(90)unique not null,
                          password varchar2(20)not null,
                          address varchar2(200)not null);                     

alter table user_details add  user_wallet number  default '50000';
update  user_details set user_wallet=0 where user_id=105;

alter table user_details add Role varchar2(20) default 'user';
insert into user_details (user_name,email_id,password,address,role) values ('Atchaya','atchaya10@gmail.com','atchayapandi','Madurai','Admin');
--insert into user_details (user_name,email_id,password,address)values('premalatha','prema12@gmail.com','premaprema','maduraiMDU620110');

select*from user_details;
commit;
select user_wallet from user_details where user_id =120;
commit;
select *from product_details;
alter table product_details modify picture varchar2(2000);
commit;
update product_details set picture='https://www.pngitem.com/pimgs/m/562-5621484_kek-png-page-bakery-cake-hd-images-png.png'
where cake_id=115;




create table help_support (phone number(15),Email varchar2(100));
insert into help_support values(8610970796,'atchaya10@gmail.com');
select * from help_support;

---PRODUCT DETAILS TABLE---
create table product_details(cake_id int default P_ID.nextval primary key ,
                      cake_name varchar2(30)not null,
                      cake_description varchar2(100)not null,
                      cake_price int not null,
                      category_name varchar2(20)not null);
                      desc product_details;
                      select* from product_details;
                      
create sequence P_ID increment by 1 start with 111;  
desc product_details;
alter table product_details drop column kilogram;
alter table product_details add Ratings number;
select*from product_details;
select user_id from user_details where email_id='prema12@gmail.com';

alter table product_details add rating number default 0;
alter table product_details add ratings number not null;
alter table product_details drop column ratings;

insert into product_details (cake_name,cake_description,cake_price,category_name) values ('Truffle Cake' ,'made with a chocolate ganache centre coated in chocolate',1025,'butter');
insert into product_details (cake_name,cake_description,cake_price,category_name) values ('Butterscotch Cake','The cake layers are made with brown sugar which is the primary ingredient of butterscotch',1030,'chocolate');
insert into product_details (cake_name,cake_description,cake_price,category_name) values ('Black Forest Cake','chocolate sponge cake, cherries, and whipped cream',1050,'Biscuit');
insert into product_details (cake_name,cake_description,cake_price,category_name) values ('Fresh Fruit Cake','cake made with chopped candied fruit and/or dried fruit, nuts, and spices',1900,'Baked Flourless Cake');
insert into product_details (cake_name,cake_description,cake_price,category_name) values ('Pinapple Cake','scratch with crushed pineapple and topped',1500,'Sponge Cake');
insert into product_details (cake_name,cake_description,cake_price,category_name) values ('Caramel Cake','Salted Caramel',1700,'Genoise Cake');
insert into product_details (cake_name,cake_description,cake_price,category_name) values('Strawberry Cake',' scone that is split and filled with strawberries and sweetened whipped cream',2000,'pound cake');
insert into product_details (cake_name,cake_description,cake_price,category_name) values('Oreo Cake',' caramel flavour filling and coloured sprinkles',1300,'Sponge Cake');
insert into product_details (cake_name,cake_description,cake_price,category_name) values('Blueberry','butter and dust with flour and line the bottom with parchment paper',1400,'butter');
insert into product_details (cake_name,cake_description,cake_price,category_name) values('White Forest','white cake with vanilla extract in the mixture',1200,'Biscuit');

commit;

---ORDER DETAILS TABLE---
create table cart_items(cart_id int generated BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1),
                       cake_id int, 
                      user_id int,                       
                     order_quantity int not null,                    
                     total_price number(10,2) not null,
                     order_date Date not null,
                     foreign  key (cake_id) references product_details(cake_id) , 
                     foreign key (user_id) references user_details(user_id));
      
select*from cart_items;      
alter table cart_items add primary key (cart_id); 
desc cart_items;

drop table cart_items;

--create table invoice_details (invoice_id int GENERATED BY DEFAULT AS IDENTITY START WITH 20 INCREMENT BY 1,
--                     cake_id int,                     
--                     user_id int,                     
--                     cart_id int,                                                            
--                     primary key(invoice_id),
--                     foreign key (cake_id) references product_details(cake_id),
--                     foreign key (user_id) references user_details(user_id),
--                     foreign key (cart_id) references cart_items(cart_id));
                     
--create table payment_details (card_no number(16) ,expire_date date,paid_amount number); 
 
-- drop table payment_details;
                     
--select*from invoice;
--drop table invoice;
select * from cart_items;   
select * from product_details;
select * from user_details;
select*from payment_details;


commit;
desc invoice;

